### ISSUE TITLE
missing 1.6_tfModules_asDF.Rds  file

### ISSUE THREAD

**Issue by KabitaBaral1** [aertslab/SCENIC#128]
Hi,

I used pySCENIC to run GRNBoost and imported the output to SCENIC using the following code:

GRNBoost_output <- read.delim("/Users/kabitabaral/Desktop/SCENIC/data/adjacencies.tsv")
colnames(GRNBoost_output) <- c("TF","Target","weight")
saveRDS(GRNBoost_output, file="/Users/kabitabaral/Desktop/int/1.4_GENIE3_linkList.Rds")

But, I am missing the file: 1.6_tfModules_asDF.Rds  from getting generated and when I try to run the next step in SCENIC, that is:

runSCENIC_1_coexNetwork2modules(scenicOptions)

I get the following error:
14:06	Creating TF modules
     75%      90% 
1.534220 4.675815 
            [,1]
nTFs         150
nTargets    1734
nGeneSets    898
nLinks    581526
Error in corrMat[tf, targets] : subscript out of bounds

Are the two issues related? the missing file and "subscript out of bounds" error?

How can I fix this error?

Thank you

**Comment by danwee** [comment]
Hi @KabitaBaral1 ,

I have the same issue before but I'm not sure if this would help. I guess you have to use the filtered gene expression matrix to run the GRNBoost first then only import in SCENIC (I mean the same loom file to run in both GRNBoost and SCENIC). 

Thanks.
Dan

**Comment by KabitaBaral1** [comment]
Hi @danwee ,

I tried this but it did not fix the issue for me. Did this fix the issue for you?
Thank you

**Comment by morganee261** [comment]
Hello @KabitaBaral1  and @danwee,

I am having the same issue, since my dataset is too big for GENIE3 I used the CLI and GRNBoost and I am importing the results in R to complete the SCENIC script. I am missing the same files as you and I am not sure which ones they are.
@cflerin would you be able to help or point us to a tutorial ?

thanks
morgane

**Comment by cflerin** [comment]
I don't usually run the analysis this way (python -> R), but the error:
```
Error in corrMat[tf, targets] : subscript out of bounds
```
makes me think that maybe a different expression matrix (or set of TFs) is being used in python GRNBoost2 vs the R steps. Otherwise, it could be that some of the steps in the R tutorial were skipped. Things are run in a slightly different order in python vs R, especially the correlation calculation, so maybe try re-running this step after loading the expression matrix and GRN output into R...

**Comment by jwg054000** [comment]
I'm also having the same issue:

Error in corrMat[tf, targets] : subscript out of bounds
