### ISSUE TITLE
The outputs are instable

### ISSUE THREAD

**Issue by XinWang19** [aertslab/SCENIC#221]
Hi,

I ran SCENIC on my single cell dataset (about 900 cells) twice, with a difference of 14 cells. However, I found there were considerable amount of regulons differing after I added these 14 cells (as following). How could I ensure the reproduciblity between the datasets? Thanks!

![image](https://user-images.githubusercontent.com/37723649/132005952-cd3bde33-755d-41de-b60b-5bbdada485d0.png)

Xin

**Comment by s-aibar** [comment]
Dear @XinWang19 ,

This issue was addressed in https://www.nature.com/articles/s41596-020-0336-2 . At the moment the solution we recommend is to run SCENIC several times to assess the stability of the results. This automated in [VSN-pipelines](https://vsn-pipelines.readthedocs.io/en/latest/pipelines.html#scenic-multiruns-scenic-multiruns-single-sample-scenic-multiruns) (i.e. see "Scenic multiruns").

I hope this helps
