### ISSUE TITLE
hg19-500bp-upstream-7species.mc9nr.feather file is not available for download

### ISSUE THREAD

**Issue by ZainulArifin1** [aertslab/SCENIC#332]
Hi!

I tried performing a tutorial of scenic with R on this [page](http://htmlpreview.github.io/?https://github.com/aertslab/SCENIC/blob/master/inst/doc/SCENIC_Running.html). But I had trouble with initializing scenic with "initializeScenic" function because hg19-500bp-upstream-7species.mc9nr.feather is not available in https://resources.aertslab.org/. 

Is there an equivalent of this file or is there a link to a repo where I can download this file from?
Thank you.

**Comment by tfguinan** [comment]
Hi there,
I'm in the same boat as you, unable to follow the setup [vignette](https://htmlpreview.github.io/?https://github.com/aertslab/SCENIC/blob/master/inst/doc/SCENIC_Setup.html#species-specific-databases:~:text=For%20human) due to 404 error.

After having a look through the index of https://resources.aertslab.org/ I came across an 'old' directory with similar data: https://resources.aertslab.org/cistarget/databases/old/homo_sapiens/hg19/refseq_r45/mc9nr/gene_based/

From the naming conventions the hg19-500bp-upstream-7species and hg19-tss-centered-5kb-7species .mc9nr.feather should be somewhat equivalent to those outlined albeit with a lower kb/TSS region. Perhaps I'm mistaken but I suspect the 5kb data reflects that of the 2017 publication (5kb up/down for 10kb around the TSS).

The .mc9nr.feather(s) are downloading, and I'll test them in SCENIC referring to the introduction vignette.
Maybe a member of the team could clarify distinctions of these various databases for us.

Cheers.

**Comment by tfguinan** [comment]
Hi just following up - I was able to successfully run 'initializeScenic' using the aforementioned datasets. 'scenicOptions' was also valid input for a number of the downstream functions.
