### ISSUE TITLE
What's goal dividing the original gene list into nParts pieces

### ISSUE THREAD

**Issue by eleozzr** [aertslab/SCENIC#41]
What's the function of parameter `nParts` in `runGenie3 `  function. In practice, how we specify the `nParts`.  

#SCENIC/R/runGenie3.R, line 30
`genesSplit <- split(sort(rownames(exprMat)), 1:nParts)` 
and I don't understand why you use `sort`? Shouldn't we put all genes together to infer gene regulatory networks from gene expression data??

**Comment by s-aibar** [comment]
Hello,

Yes, all genes are used to infer the regulatory networks, but each gene can be calculated individually. Since it big datasets it can take several hours/days to run GENIE3 for all the genes, the execution is split into pieces to avoid the loss of the full run in case it is interrupted. This is not required, but rather a workaround for those users that cannot/do not want to use GRNBoost (the recommended method).
