### ISSUE TITLE
error at RcisTarget, R session Aborted

### ISSUE THREAD

**Issue by fangge-Li** [aertslab/SCENIC#51]
Hi there,
   I ran the R code. At the step, 
               library(RcisTarget)
              motifRankings <- importRankings(getDatabases(scenicOptions)
  R session aborted.

  I searched the answer from other issues. The reason might be the databases are incomplete/corrupt. Follow the tutorial, only dm6-5kb-upstream-full-tx-11species.mc8nr.feather  was downloaded in my local folder. I tried to download dm6-regions-11species.mc8nr.feather.

However, I found there is no region_based folder in this link,       https://resources.aertslab.org/cistarget/databases/drosophila_melanogaster/dm6/flybase_r6.02/mc8nr/
 I am not sure whether dm6-regions-11species.mc8nr.feather is necessary in SCENIC.
 Without  dm6-regions-11species.mc8nr.feather, was it the reason of R session aborted? 

Thank you!

**Comment by s-aibar** [comment]
Dear @fangge-Li ,

For running SCENIC you only need the "[gene-based](https://resources.aertslab.org/cistarget/databases/drosophila_melanogaster/dm6/flybase_r6.02/mc8nr/gene_based/)" databases. The "region" databases are for other types of analyses. 

The R session aborted indeed seems to happen when the databases are incomplete/corrupt. 
We recommended to download the databases is using zsync_curl (https://resources.aertslab.org/cistarget/help.html). Once you have the files, make sure the sha256sum match the reported ones (https://resources.aertslab.org/cistarget/databases/sha256sum.txt). Also, you can check that you are using the latest R feather package (version 0.3.1, previous versions are more likely to crash due to this error).
