### ISSUE TITLE
there's no geneFiltering function

### ISSUE THREAD

**Issue by zxystarrian** [aertslab/SCENIC#52]
Hi,

I just followed the tutorial of Running SCENIC. But I encountered an error when I ran:
`genesKept <- geneFiltering(exprMat, scenicOptions=scenicOptions,
                           minCountsPerGene=3*.01*ncol(exprMat),
                           minSamples=ncol(exprMat)*.01)`

It looks like a function within SCENIC, but I can't find it. Could you please tell me which package it is from? I have libraried all the packages which are suggested to have for this tutorial.

Thanks!

Best,
Xingyu

**Comment by MichaelPeibo** [comment]
@zxystarrian 
Hi, I got same error, it could be due to the recent update of functions.

simply you can add this function by yourself, detail of function is here:

        SCENIC/R/aux_geneFiltering.R
      
here is code:
`geneFiltering <- function(exprMat, scenicOptions,
                          minCountsPerGene=3*.01*ncol(exprMat),
                          minSamples=ncol(exprMat)*.01)
{
  # Load options: outFile_genesKept and dbFilePath
  outFile_genesKept <- NULL
  dbFilePath <- NULL
  if(class(scenicOptions) == "ScenicOptions")
  {
    dbFilePath <- getDatabases(scenicOptions)[[1]]
    outFile_genesKept <- getIntName(scenicOptions, "genesKept")
  }else{
    dbFilePath <- scenicOptions[["dbFilePath"]]
    outFile_genesKept <- scenicOptions[["outFile_genesKept"]]
  }
  if(is.null(dbFilePath)) stop("dbFilePath")
  
  
  # Calculate stats
  nCountsPerGene <- rowSums(exprMat, na.rm = T)
  nCellsPerGene <- rowSums(exprMat>0, na.rm = T)
  
  ## Show info
  message("Maximum value in the expression matrix: ", max(exprMat, na.rm=T))
  message("Ratio of detected vs non-detected: ", signif(sum(exprMat>0, na.rm=T) / sum(exprMat==0, na.rm=T), 2))
  message("Number of counts (in the dataset units) per gene:")
  print(summary(nCountsPerGene))
  message("Number of cells in which each gene is detected:")
  print(summary(nCellsPerGene))

  ## Filter
  message("\nNumber of genes left after applying the following filters (sequential):")
  # First filter
  # minCountsPerGene <- 3*.01*ncol(exprMat)
  genesLeft_minReads <- names(nCountsPerGene)[which(nCountsPerGene > minCountsPerGene)]
  message("\t", length(genesLeft_minReads), "\tgenes with counts per gene > ", minCountsPerGene)
  
  # Second filter
  # minSamples <- ncol(exprMat)*.01
  nCellsPerGene2 <- nCellsPerGene[genesLeft_minReads]
  genesLeft_minCells <- names(nCellsPerGene2)[which(nCellsPerGene2 > minSamples)]
  message("\t", length(genesLeft_minCells), "\tgenes detected in more than ",minSamples," cells")
  
  # Exclude genes missing from database:
  library(RcisTarget)
  motifRankings <- importRankings(dbFilePath) # either one, they should have the same genes
  genesInDatabase <- colnames(getRanking(motifRankings))
  
  genesLeft_minCells_inDatabases <- genesLeft_minCells[which(genesLeft_minCells %in% genesInDatabase)]
  message("\t", length(genesLeft_minCells_inDatabases), "\tgenes available in RcisTarget database")
  
  genesKept <- genesLeft_minCells_inDatabases
  if(is.null(outFile_genesKept)) 
    saveRDS(genesKept, file=outFile_genesKept)
    
  return(genesKept)
}`

Good luck!
