### ISSUE TITLE
"Error in metadataFeather(path) : IO error: Failed to open file" in genefiltering()

### ISSUE THREAD

**Issue by chent5** [aertslab/SCENIC#63]
Hi,

SCENIC will be very helpful for my project. I am learning SCENIC using SCENIC_myRun.Rmd you provided online. I keep on geting an error message when I run geneFiltering() function: 
Error in metadataFeather(path) : IO error: Failed to open file

Below is my code:  
<img width="721" alt="screen shot 2019-01-20 at 10 11 17 pm" src="https://user-images.githubusercontent.com/40006284/51450891-95af2600-1d00-11e9-91b5-3914e959b217.png">

<img width="764" alt="screen shot 2019-01-20 at 10 11 39 pm" src="https://user-images.githubusercontent.com/40006284/51450915-bb3c2f80-1d00-11e9-8198-ee21874ccafd.png">

I re-downloaded the databases and tried it again, but still got the same error message...

Could you help me to figure out this problem? Thank you so much!

**Comment by s-aibar** [comment]
Hello,

It seems you are having trouble loading the motif databases... Can you check whether you can run this code? (it attempts to read the databases): 

```
dbFilePath <- getDatabases(scenicOptions)[[1]]
importRankings(dbFilePath)
```

It will probably fail; either because the database path is not set properly, or because the databases are corrupt (e.g. problem downloading, if that is the case you can check: https://resources.aertslab.org/cistarget/help.html)

For more details you can also see the vignette that explains that function:
https://github.com/aertslab/SCENIC/blob/master/vignettes/detailedStep_0_geneFilter.Rmd

**Comment by chent5** [comment]
I re-downloaded the databases with zsync_curl. But still not working... Please see the screen shot below.
<img width="657" alt="image" src="https://user-images.githubusercontent.com/40006284/51958147-9a6c8c00-241c-11e9-9a16-3da73324ebf9.png">
As I posted initially, when I created scenicOptions using initializeScenic(), it showed "Motif databases selected: mm9-500bp-upstream-7species.mc9nr.feather, mm9-tss-centered-10kb-7species.mc9nr.feather". But when I ran geneFiltering(), it showed "Error in metadataFeather(path) : IO error: Failed to open file: ".

I also got error message why I tried importRankings().
<img width="700" alt="image" src="https://user-images.githubusercontent.com/40006284/51958436-cb998c00-241d-11e9-8caa-eb89cce9bb5e.png">

Any ways to solve this problem? Thank you so much!

**Comment by s-aibar** [comment]
Dear @chent5,

It seems that the function "feather_metadata" doesn't understand the symbol `~` in the path: 
```
md <- feather::feather_metadata("~/motif_databases/mm9-tss-centered-10kb-7species.mc9nr.feather")
# Error in metadataFeather(path) :  IO error: Failed to open file: ~/motif_databases/mm9-tss-centered-10kb-7species.mc9nr.feather

md <- feather::feather_metadata("databases/mm9-tss-centered-10kb-7species.mc9nr.feather")
# Works fine
```

I will try to check for this within RcisTarget/SCENIC code, but meanwhile you can use the full path instead of "~" (e.g. /home/yourusername/...) or create a link (e.g. in linux/mac: `ln -s ~/path/to/folder link_name`).

If this still doesn't solve the issue, then I will probably need to know what are your R and package versions (SCENIC, RcisTarget, feather)...

Thanks for the report!

**Comment by chent5** [comment]
Thank you so much. It works!
