### ISSUE TITLE
apply to zebrafish

### ISSUE THREAD

**Issue by yongjieliu** [aertslab/SCENIC#67]
hello~

I want to know if this method can be used on zebrafish.

**Comment by s-aibar** [comment]
Dear @yongjieliu ,

At the moment we only provide the motif databases (required for the standard pipeline) for human, mouse and fruit fly. 

The second step in SCENIC's workflow is to perform motif enrichment analysis on the co-expression modules to prune them into regulons. The standard SCENIC pipeline uses RcisTarget to perform this analysis, and RcisTarget requires species-specific databases. 
Therefore, to apply SCENIC to a new organism (such as zebrafrish) would require some modifications on this step. Either creating the RcisTarget motif databases for the new organism (which implies defining regulatory regions and scoring thousands of motifs PWM), or using an alternative tool (i.e. instead of RcisTarget) for the motif analysis.
