### ISSUE TITLE
Scale of GRNBoost Results

### ISSUE THREAD

**Issue by AsafPoran** [aertslab/SCENIC#7]
Hi! first, thanks for the detailed installation guide and tutorials, they were very useful! I was hoping you could help me understand how to integrate the data from the GRNBoost procedure which speeds-up the GENIE3 process. 
Whereas GENIE3 returns a weighted adjacency matrix where the weights are fractional values between 0-1, the GRNBoost returns a list with the weights ranging to about 1E9.
I was wondering if something had gone wrong in the GRNBoost procedure (though no errors were reported) or is there a normalization step I am missing?

Thanks!

**Comment by s-aibar** [comment]
Hello,

I am not very familiar with the exact output of GRNBoost, but if I remember correctly, I think it provides a result similar to GENIE3 after converting the weightMatrix to linkList (e.g. `getLinkList(weightMatrix)` ). 

The scales of the weights might be different, but that should not matter too much, since they are mostly used to "rank" the TFs. You will only need to adjust the threshold in the next step of SCENIC, to create the gene-sets (co-expression modules) to analyse for motif enrichment.

**Comment by tmoerman** [comment]
Hello,
indeed, the weights carry no other meaning than the ranking in the list of regulatory links.

**Comment by AsafPoran** [comment]
Great, thanks for the clarification!
