### ISSUE TITLE
restart Genie3 where crashed

### ISSUE THREAD

**Issue by ONeillMB1** [aertslab/SCENIC#98]
Hello. I am wondering if it is possible to restart the runGenie3 function where it left off - my computer crashed after it had been running for >1 week.

**Comment by s-aibar** [comment]
Not automatically, but you might have some files with partial results... you can use those to see which genes were already run, and start a new run with the remaining ones...

**Comment by Ivalyne** [comment]
Hi. Thank you for the wonderful package.
I've almost same question about the runGENIE3 function.

Because of limitation of my computing server's memory(but it has >500GB RAM),
sometime my command also crushed after it had been running several days.

As you @s-aibar mentioned, runGENIE3 created files, series of 1.3_GENIE3_weightMatrix_part_x.Rds.
But I'm not sure about how to use these files when I re-run the function again.

Would you kindly tell us the specific commands?
Thanks.

**Comment by s-aibar** [comment]
Dear @Ivalyne , 

The function runGENIE3 now allows to resume the execution, you can just set `resumePreviousRun=TRUE` and it will re-load the previous partial runs (but make sure you are using the same settings...). 

I hope it is useful!

**Comment by Ivalyne** [comment]
Thank you for replying so quickly.

Because I had forgotten to update the package, I still use older version.
I'll update it to latest.

In case of the function runGENIE3 crash again ( I hope it will never happen),
I will set the argument.

Many thanks.
