### ISSUE TITLE
Error loading .loom file created using Seurat in SCENIC

### ISSUE THREAD

**Issue by JoaoGabrielMoraes** [aertslab/SCENIC#99]
Hello SCENIC community!

I am trying to load a loom file created using Seurat in SCENIC and I am getting the following error:
```
> loomPath <- system.file(package="SCENIC", ".../PATH/singlecell_combined.loom")
> library(SCopeLoomR)
> loom <- open_loom(loomPath, mode="r")
Error in H5File.open(filename, mode, file_create_pl, file_access_pl) : 
  HDF5-API Errors:
    error #000: H5F.c in H5Fopen(): line 491: invalid file name
        class: HDF5
        major: Invalid arguments to routine
        minor: Bad value
```
Any ideas on how to fix this?

Thank you!!

**Comment by s-aibar** [comment]
I am not familiar with that specific error, but it seems that there is something wrong with the path, possible options: 
- does the path include `~`? (sometimes it is not extended properly)
- avoid using relative paths with `.` or `..` (I guess the *3* dots in your example are just for the example... ;) )
- does the path contain any non standard characters?
- does the file exist?
- is the loom "closed" -> It is quite common to get error because the loom was already open (e.g. by another script, or it was never finalized/closed...)

**Comment by rstatistics** [comment]
After I installed the current version of "hdf5r", the error message gone.
So, perhaps you should update the version of hdf5 ≥ 1.8.13, and then install the latest version of hdf5r.
I hope it works for you!
